#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0-{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  only:
    - master

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\trax

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# environment variables
environment:
  INSTALL_DIR: c:\projects\trax\trax
  matrix:

    - GENERATOR: "Visual Studio 12 2013 Win64"
      BUILD_PLATFORM: windows64_vs12
      OPENCV_VERSION: 2.4.13

    - GENERATOR: "Visual Studio 14 2015 Win64"
      BUILD_PLATFORM: windows64_vs14
      OPENCV_VERSION: 3.1.0.20160701

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
   - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
    - Release

# scripts that run after cloning repository
install:
  - cmd: choco install OpenCV -y -version %OPENCV_VERSION%

build_script:
  - IF EXIST c:\tools\opencv* CD c:\tools\opencv*
  - SET OPENCV_DIR=%CD%\build
  - echo Running cmake...
  - cd c:\projects\trax
  - set /p BUILD_VERSION=< VERSION
  - appveyor UpdateBuild -Version "%BUILD_VERSION%-%APPVEYOR_BUILD_NUMBER%"
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DBUILD_CLIENT=ON -DBUILD_OPENCV=ON -DOpenCV_DIR=%OPENCV_DIR% -DBUILD_PLATFORM=%BUILD_PLATFORM% .
  - msbuild INSTALL.vcxproj /p:Configuration=Debug /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild INSTALL.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - 7z a -tzip trax-%BUILD_VERSION%-%BUILD_PLATFORM%.zip trax/*

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: trax-*.zip
    name: trax

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:

  - provider: FTP
    protocol: ftp
    host: box.vicos.si
    username:
      secure: bDHnDKIt8ViL7omIcl/oSQ==
    password:
      secure: iUkFvVxZhfw9FG4FC7YqxQ==
    folder: /vot/trax/
    application:
    active_mode: false
    beta: true      # enable alternative FTP library for 'ftp' and 'ftps' modes
    debug: true     # show complete FTP log
    artifact: trax
  - provider: BinTray
    username:
      secure: Pj3SA0paaY9ttXiqhO3Ktw==
    api_key:
      secure: MNgt5hxXPUBXZbzzQ4fVHfl6f4A3Koile2Ebc0iCLCDl2LxexlLLxlFXEIDc/h3o
    subject: votchallenge
    repo: trax
    package: stable
    version: $(BUILD_VERSION)
    publish: true
    override: true
    explode: false
    artifact: trax

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - luka.cehovin@gmail.com
    subject: 'TraX Build {{status}}'
    message: "TraX library Windows build status for {{commitId}} = {{status}}"
    on_build_status_changed: true

